services:

  gitlab:
    image: gitlab/gitlab-ce:latest    # 19.2.0-ce.0
    container_name: gitlab
    restart: unless-stopped
    stop_grace_period: 5m
    shm_size: "256m"
    volumes:
      - ./config:/etc/gitlab
      - ./data:/var/opt/gitlab
      - ./logs:/var/log/gitlab
    ports:
      - "8200:80"
      - "2222:22"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url "http://localhost:8200"   # cambiar IP:8200 ó dominio
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        letsencrypt['enable'] = false
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
